// <auto-generated />
using System;
using BeanSceneReservationSystemProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeanSceneReservationSystemProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523200307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AreaId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            AreaName = "Main"
                        },
                        new
                        {
                            AreaId = 2,
                            AreaName = "Outside"
                        },
                        new
                        {
                            AreaId = 3,
                            AreaName = "Balcony"
                        });
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GuestLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SittingId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("MemberId");

                    b.HasIndex("SittingId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.ReservationStatusHistory", b =>
                {
                    b.Property<int>("ReservationStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationStatusHistoryId"));

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("ReservationStatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationStatusHistories");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.ReservationTable", b =>
                {
                    b.Property<int>("ReservationTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationTableId"));

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantTableId")
                        .HasColumnType("int");

                    b.HasKey("ReservationTableId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RestaurantTableId");

                    b.ToTable("ReservationTables");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.RestaurantTable", b =>
                {
                    b.Property<int>("RestaurantTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantTableId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RestaurantTableId");

                    b.HasIndex("AreaId");

                    b.HasIndex("TableCode")
                        .IsUnique();

                    b.ToTable("RestaurantTables");

                    b.HasData(
                        new
                        {
                            RestaurantTableId = 1,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M1"
                        },
                        new
                        {
                            RestaurantTableId = 2,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M2"
                        },
                        new
                        {
                            RestaurantTableId = 3,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M3"
                        },
                        new
                        {
                            RestaurantTableId = 4,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M4"
                        },
                        new
                        {
                            RestaurantTableId = 5,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M5"
                        },
                        new
                        {
                            RestaurantTableId = 6,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M6"
                        },
                        new
                        {
                            RestaurantTableId = 7,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M7"
                        },
                        new
                        {
                            RestaurantTableId = 8,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M8"
                        },
                        new
                        {
                            RestaurantTableId = 9,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M9"
                        },
                        new
                        {
                            RestaurantTableId = 10,
                            AreaId = 1,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "M10"
                        },
                        new
                        {
                            RestaurantTableId = 11,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O1"
                        },
                        new
                        {
                            RestaurantTableId = 12,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O2"
                        },
                        new
                        {
                            RestaurantTableId = 13,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O3"
                        },
                        new
                        {
                            RestaurantTableId = 14,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O4"
                        },
                        new
                        {
                            RestaurantTableId = 15,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O5"
                        },
                        new
                        {
                            RestaurantTableId = 16,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O6"
                        },
                        new
                        {
                            RestaurantTableId = 17,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O7"
                        },
                        new
                        {
                            RestaurantTableId = 18,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O8"
                        },
                        new
                        {
                            RestaurantTableId = 19,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O9"
                        },
                        new
                        {
                            RestaurantTableId = 20,
                            AreaId = 2,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "O10"
                        },
                        new
                        {
                            RestaurantTableId = 21,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B1"
                        },
                        new
                        {
                            RestaurantTableId = 22,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B2"
                        },
                        new
                        {
                            RestaurantTableId = 23,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B3"
                        },
                        new
                        {
                            RestaurantTableId = 24,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B4"
                        },
                        new
                        {
                            RestaurantTableId = 25,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B5"
                        },
                        new
                        {
                            RestaurantTableId = 26,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B6"
                        },
                        new
                        {
                            RestaurantTableId = 27,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B7"
                        },
                        new
                        {
                            RestaurantTableId = 28,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B8"
                        },
                        new
                        {
                            RestaurantTableId = 29,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B9"
                        },
                        new
                        {
                            RestaurantTableId = 30,
                            AreaId = 3,
                            Capacity = 4,
                            IsAvailable = true,
                            TableCode = "B10"
                        });
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Sitting", b =>
                {
                    b.Property<int>("SittingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SittingId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("SittingType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SittingId");

                    b.ToTable("Sittings");

                    b.HasData(
                        new
                        {
                            SittingId = 1,
                            Capacity = 40,
                            EndDateTime = new DateTime(2026, 6, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClosed = false,
                            SittingType = 0,
                            StartDateTime = new DateTime(2026, 6, 1, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SittingId = 2,
                            Capacity = 50,
                            EndDateTime = new DateTime(2026, 6, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClosed = false,
                            SittingType = 1,
                            StartDateTime = new DateTime(2026, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SittingId = 3,
                            Capacity = 60,
                            EndDateTime = new DateTime(2026, 6, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClosed = false,
                            SittingType = 2,
                            StartDateTime = new DateTime(2026, 6, 1, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Member", b =>
                {
                    b.HasOne("BeanSceneReservationSystemProject.Models.User", "User")
                        .WithOne("MemberProfile")
                        .HasForeignKey("BeanSceneReservationSystemProject.Models.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Reservation", b =>
                {
                    b.HasOne("BeanSceneReservationSystemProject.Models.Member", "Member")
                        .WithMany("Reservations")
                        .HasForeignKey("MemberId");

                    b.HasOne("BeanSceneReservationSystemProject.Models.Sitting", "Sitting")
                        .WithMany("Reservations")
                        .HasForeignKey("SittingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Sitting");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.ReservationStatusHistory", b =>
                {
                    b.HasOne("BeanSceneReservationSystemProject.Models.User", "ChangedByUser")
                        .WithMany("StatusChanges")
                        .HasForeignKey("ChangedByUserId");

                    b.HasOne("BeanSceneReservationSystemProject.Models.Reservation", "Reservation")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.ReservationTable", b =>
                {
                    b.HasOne("BeanSceneReservationSystemProject.Models.Reservation", "Reservation")
                        .WithMany("ReservationTables")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeanSceneReservationSystemProject.Models.RestaurantTable", "RestaurantTable")
                        .WithMany("ReservationTables")
                        .HasForeignKey("RestaurantTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.RestaurantTable", b =>
                {
                    b.HasOne("BeanSceneReservationSystemProject.Models.Area", "Area")
                        .WithMany("RestaurantTables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Area", b =>
                {
                    b.Navigation("RestaurantTables");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Member", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Reservation", b =>
                {
                    b.Navigation("ReservationTables");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.RestaurantTable", b =>
                {
                    b.Navigation("ReservationTables");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.Sitting", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BeanSceneReservationSystemProject.Models.User", b =>
                {
                    b.Navigation("MemberProfile");

                    b.Navigation("StatusChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
